// site/src/app/page.tsx
"use client";

import * as React from 'react';
import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import CardHeader from '@mui/material/CardHeader';
import CssBaseline from '@mui/material/CssBaseline';
import Grid from '@mui/material/Grid';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import GlobalStyles from '@mui/material/GlobalStyles';
import Container from '@mui/material/Container';
import TextField from '@mui/material/TextField';
import Autocomplete from '@mui/material/Autocomplete';
import { ThemeProvider, createTheme } from '@mui/material/styles';
import { Chart as ChartJS, CategoryScale, LinearScale, BarElement, Title, Tooltip, Legend } from 'chart.js';
import { Bar } from 'react-chartjs-2';

// Chart initialization
ChartJS.register( CategoryScale, LinearScale, BarElement, Title, Tooltip, Legend );
ChartJS.defaults.backgroundColor = '#9BD0F5';
ChartJS.defaults.borderColor = '#36A2EB';
ChartJS.defaults.color = '#FFFFFF';
var chartData : any = {};

// Dark theme
const darkTheme = createTheme({
  palette: {
    mode: 'dark',
  },
});

function RainfallContent() {
  const [data, setData] = React.useState(null);

  React.useEffect(() => {
    // URL parameters
    let uri = window.location.search.substring(1);
    let params = new URLSearchParams(uri);
    var input_site = Number(params.get("site")) || 2959

    // API request
    fetch(
      'https://rainfall-data-67ugd5bjtq-uc.a.run.app',
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ site: input_site }),
      }
    )
      .then(response => response.json())
      .then(json => setData(json))
      .catch(error => console.error(error));
  }, []);

  const listOfSites = data ? data["list_of_sites"] : [];
  const [value, setValue] = React.useState<string | null>(listOfSites[0]);
  const [inputValue, setInputValue] = React.useState('');

  // Chart data
  chartData = {
    labels: [
      "Last 1 hour",
      "Last 3 hours",
      "Last 6 hours",
      "Last 24 hours",
      "Since midnight",
      "1 day ago",
      "2 days ago",
      "3 days ago",
      "4 days ago",
      "5 day total",
    ],
    datasets: [
      {
        label: "Rainfall Amount",
        backgroundColor: "#0ea5e9",
        borderColor: "#222222",
        color: "#222222",
        data: [
          data ? data["rainfall_amounts"][0]["Last 1 hour"] : 0,
          data ? data["rainfall_amounts"][0]["Last 3 hours"] : 0,
          data ? data["rainfall_amounts"][0]["Last 6 hours"] : 0,
          data ? data["rainfall_amounts"][0]["Last 24 hours"] : 0,
          data ? data["rainfall_amounts"][0]["Since midnight"] : 0,
          data ? data["rainfall_amounts"][0]["1 day ago"] : 0,
          data ? data["rainfall_amounts"][0]["2 days ago"] : 0,
          data ? data["rainfall_amounts"][0]["3 days ago"] : 0,
          data ? data["rainfall_amounts"][0]["4 days ago"] : 0,
          data ? data["rainfall_amounts"][0]["5 day total"] : 0,
        ],
      },
    ],
  };

  const options : any = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        display: false,
      },
    },
    scales: {
      y: {
        ticks: {
          suggestedMin: 0,
        },
        title: {
          display: true,
          text: "Rainfall Amount (in)",
        },
      },
    },
  };

  return (
    <ThemeProvider theme={darkTheme}>
      <React.Fragment>
        <GlobalStyles styles={{ ul: { margin: 0, padding: 0, listStyle: 'none' } }} />
        <CssBaseline />
        <AppBar
          position="static"
          color="default"
          elevation={0}
          sx={{ borderBottom: (theme) => `1px solid ${theme.palette.divider}` }}
        >
          <Toolbar sx={{ flexWrap: 'wrap' }}>
            <Typography variant="h5" color="inherit" noWrap sx={{ flexGrow: 1, fontWeight: 'bold' }}>
              Central Texas Rainfall Totals
            </Typography>
          </Toolbar>
        </AppBar>

        <Grid container spacing={3} sx={{ p:4 }} alignItems="center">
        <Grid item>
          <Typography variant="h6" align="left" color="text.secondary" component="p">
            Showing rainfall from the
          </Typography>
        </Grid>
        <Grid item>
          <Autocomplete
            disablePortal
            disableClearable
            defaultValue={{ location: "Marble Falls 4 WSW" }}
            size="small"
            id="sites"
            options={listOfSites}
            getOptionLabel={(data: {location: string}) => data.location}
            sx={{ width: 250 }}
            renderInput={(params) => <TextField {...params} />}
          />
        </Grid>
          <Grid item>
            <Typography variant="h6" align="left" color="text.secondary" component="p">
              LCRA Hydromet weather gauge
            </Typography>
          </Grid>
        </Grid>
        <Container maxWidth="lg" component="main">
          <Grid container spacing={5} alignItems="flex-end" sx={{ pb: 4 }}>
              <Grid item xs={12} sm={6} md={4}>
                <Card>
                  <CardHeader
                    title={data ? data["rainfall_amounts"][0]["Since midnight"] + " in" : 'Loading...'}
                    titleTypographyProps={{ align: 'center' }}
                    subheaderTypographyProps={{
                      align: 'center',
                    }}
                    sx={{
                      backgroundColor: (theme) =>
                        theme.palette.mode === 'light'
                          ? theme.palette.grey[200]
                          : theme.palette.grey[700],
                      p: 1,
                    }}
                  />
                  <Typography component="h5" variant="h6" color="text.primary" sx={{ display: 'flex', flexDirection: "column", justifyContent: 'center', alignItems: 'center', p: 1}}>
                    Today
                  </Typography>
                </Card>
              </Grid>
              <Grid item xs={12} sm={6} md={4}>
                <Card>
                  <CardHeader
                    title={data ? data["rainfall_amounts"][0]["5 day total"] + " in" : 'Loading...'}
                    titleTypographyProps={{ align: 'center' }}
                    subheaderTypographyProps={{
                      align: 'center',
                    }}
                    sx={{
                      backgroundColor: (theme) =>
                        theme.palette.mode === 'light'
                          ? theme.palette.grey[200]
                          : theme.palette.grey[700],
                        p: 1,
                    }}
                  />
                  <Typography component="h5" variant="h6" color="text.primary" sx={{ display: 'flex', flexDirection: "column", justifyContent: 'center', alignItems: 'center', p: 1}}>
                    Last 5 days
                  </Typography>
                </Card>
              </Grid>
              <Grid item xs={12} sm={6} md={4}>
                <Card>
                  <CardHeader
                    title={data ? data["rainfall_amounts"][0]["This year"] + " in" : 'Loading...'}
                    titleTypographyProps={{ align: 'center' }}
                    subheaderTypographyProps={{
                      align: 'center',
                    }}
                    sx={{
                      backgroundColor: (theme) =>
                        theme.palette.mode === 'light'
                          ? theme.palette.grey[200]
                          : theme.palette.grey[700],
                        p: 1,
                    }}
                  />
                  <Typography component="h5" variant="h6" color="text.primary" sx={{ display: 'flex', flexDirection: "column", justifyContent: 'center', alignItems: 'center', p: 1}}>
                    This year
                  </Typography>
                </Card>
              </Grid>
          </Grid>

          <Grid container spacing={5} alignItems="flex-end" sx={{ pb: 4 }}>
              <Grid item xs={12} sm={6} md={4}>
                <Card>
                  <CardHeader
                    title={data ? data["rainfall_amounts"][0]["1 day ago"] + " in" : 'Loading...'}
                    titleTypographyProps={{ align: 'center' }}
                    subheaderTypographyProps={{
                      align: 'center',
                    }}
                    sx={{
                      backgroundColor: (theme) =>
                        theme.palette.mode === 'light'
                          ? theme.palette.grey[200]
                          : theme.palette.grey[700],
                        p: 1,
                    }}
                  />
                  <Typography component="h5" variant="h6" color="text.primary" sx={{ display: 'flex', flexDirection: "column", justifyContent: 'center', alignItems: 'center', p: 1}}>
                    Yesterday
                  </Typography>
                </Card>
              </Grid>
              <Grid item xs={12} sm={6} md={4}>
                <Card>
                  <CardHeader
                    title={data ? data["rainfall_amounts"][0]["30 day total"] + " in" : 'Loading...'}
                    titleTypographyProps={{ align: 'center' }}
                    subheaderTypographyProps={{
                      align: 'center',
                    }}
                    sx={{
                      backgroundColor: (theme) =>
                        theme.palette.mode === 'light'
                          ? theme.palette.grey[200]
                          : theme.palette.grey[700],
                        p: 1,
                    }}
                  />
                  <Typography component="h5" variant="h6" color="text.primary" sx={{ display: 'flex', flexDirection: "column", justifyContent: 'center', alignItems: 'center', p: 1}}>
                    Last 30 days
                  </Typography>
                </Card>
              </Grid>
              <Grid item xs={12} sm={6} md={4}>
                <Card>
                  <CardHeader
                    title={data ? data["rainfall_amounts"][0]["Last year"] + " in" : 'Loading...'}
                    titleTypographyProps={{ align: 'center' }}
                    subheaderTypographyProps={{
                      align: 'center',
                    }}
                    sx={{
                      backgroundColor: (theme) =>
                        theme.palette.mode === 'light'
                          ? theme.palette.grey[200]
                          : theme.palette.grey[700],
                        p: 1,
                    }}
                  />
                  <Typography component="h5" variant="h6" color="text.primary" sx={{ display: 'flex', flexDirection: "column", justifyContent: 'center', alignItems: 'center', p: 1}}>
                    Last year
                  </Typography>
                </Card>
              </Grid>
          </Grid>
        </Container>
        <Container sx={{ height: '40vh', width: '100vw', justifyContent: 'center' }}>
          <Bar options={options} data={chartData} />
        </Container>
      </React.Fragment>
    </ThemeProvider>
  );
}

export default function Rainfall() {
  return <RainfallContent />;
}

// site/src/app/app.component.ts
import { Component } from '@angular/core';
import Chart from 'chart.js';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'rainfall-data';

  rainfall_amounts: any;
  list_of_sites: any;
  site: any;
  location: any;
  previous_1_hour: any;
  previous_3_hours: any;
  previous_6_hours: any;
  previous_24_hours: any;
  since_midnight: any;
  one_day_ago: any;
  two_days_ago: any;
  three_days_ago: any;
  four_days_ago: any;
  five_day_total: any;
  thirty_day_total: any;
  this_month: any;
  this_year: any;
  last_year: any;
  selected_site: any;

  // Trigger a change when a different site is selected
  changeSite() {
    window.location.href = "https://rainfall.koverholt.com/?site=" + this.selected_site;;
  };

  constructor() {

    // URL parameters
    let uri = window.location.search.substring(1);
    let params = new URLSearchParams(uri);
    var input_site = Number(params.get("site")) || 2959

    // Request
    var input = { "site": input_site };
    var xhr = new XMLHttpRequest();
    var self = this;
    xhr.open("POST", "https://us-central1-koverholt-apps-304316.cloudfunctions.net/rainfall-data");
    xhr.setRequestHeader("Content-Type", "application/json");
    xhr.send(JSON.stringify(input));

    xhr.onload = function () {
      var data = JSON.parse(this.response)
      self.rainfall_amounts = data.rainfall_amounts[0]
      self.list_of_sites = data.list_of_sites
      self.site = self.rainfall_amounts["site"]
      self.location = self.rainfall_amounts["location"]
      self.previous_1_hour = self.rainfall_amounts["Previous 1 hour"]
      self.previous_3_hours = self.rainfall_amounts["Previous 3 hours"]
      self.previous_6_hours = self.rainfall_amounts["Previous 6 hours"]
      self.previous_24_hours = self.rainfall_amounts["Previous 24 hours"]
      self.since_midnight = self.rainfall_amounts["Since midnight"]
      self.one_day_ago = self.rainfall_amounts["1 day ago"]
      self.two_days_ago = self.rainfall_amounts["2 days ago"]
      self.three_days_ago = self.rainfall_amounts["3 days ago"]
      self.four_days_ago = self.rainfall_amounts["4 days ago"]
      self.five_day_total = self.rainfall_amounts["5 day total"]
      self.thirty_day_total = self.rainfall_amounts["30 day total"]
      self.this_month = self.rainfall_amounts["This month"]
      self.this_year = self.rainfall_amounts["This year"]
      self.last_year = self.rainfall_amounts["Last year"]

      var xValue = ["Previous 1 hour", "Previous 3 hours", "Previous 6 hours", "Previous 24 hours", "Since midnight", "1 day ago", "2 days ago", "3 days ago", "4 days ago", "5 day total"]
      var yValue = [self.previous_1_hour, self.previous_3_hours, self.previous_6_hours, self.previous_24_hours, self.since_midnight, self.one_day_ago, self.two_days_ago, self.three_days_ago, self.four_days_ago, self.five_day_total]
      var maxYValue = Math.max(...yValue)

      const canvas = <HTMLCanvasElement>document.getElementById('myChart');
      const ctx = canvas.getContext('2d');
      var myBarChart = new Chart(ctx!, {
        type: 'bar',

        data: {
          labels: ["Last 1 hour",
            "Last 3 hours",
            "Last 6 hours",
            "Last 24 hours",
            "Since midnight",
            "1 day ago",
            "2 days ago",
            "3 days ago",
            "4 days ago",
            "5 day total"
          ],
          datasets: [{
            label: 'Rainfall Amount',
            backgroundColor: 'rgb(50, 115, 220)',
            borderColor: 'rgb(3, 87, 255)',
            data: [
              self.previous_1_hour,
              self.previous_3_hours,
              self.previous_6_hours,
              self.previous_24_hours,
              self.since_midnight,
              self.one_day_ago,
              self.two_days_ago,
              self.three_days_ago,
              self.four_days_ago,
              self.five_day_total
            ]
          }]
        },

        options: {
          responsive: true,
          maintainAspectRatio: false,
          legend: { display: false },
          scales: {
            yAxes: [{
              ticks: {
                suggestedMin: 0,
              },
              scaleLabel: {
                display: true,
                labelString: 'Rainfall Amount (in)'
              },
            }]
          },
        }

      });

      Chart.scaleService.updateScaleDefaults('linear', {
        ticks: {
          min: 0
        }
      });

      Chart.defaults.global.defaultFontSize = 13;
    }
  }
}

<section class="hero is-link is-small">
  <div class="hero-body">
    <p class="title">
      Central Texas Rainfall Totals
    </p>
    <p class="subtitle" *ngIf="location">
      Showing recent rainfall totals from the
      <select name="sitelist" id="sitelist" (change)="changeSite()">
        <option [value]="site" selected>{{ location }}</option>
        <option *ngFor="let item of list_of_sites" [value]="item.site">{{ item.location }}</option>
      </select>
      &nbsp;<a href="https://hydromet.lcra.org/">LCRA Hydromet</a> rainfall gauge site
    </p>
    <p class="subtitle" *ngIf="!location">
      &nbsp;
    </p>
  </div>
</section>

<div *ngIf="!location">
  <progress class="progress is-medium is-link" max="100"></progress>
</div>

<div class="columns mt-2" *ngIf="location">
  <div class="column">
    <div class="card has-background-link-light">
      <div class="card-content">
        <p class="title is-4 is-size-6-mobile has-text-centered">
          {{ since_midnight }} in
        </p>
        <p class="subtitle is-6 is-size-7-mobile has-text-centered">
          Since midnight
        </p>
      </div>
    </div>
  </div>
  <div class="column">
    <div class="card has-background-link-light">
      <div class="card-content">
        <p class="title is-4 is-size-6-mobile has-text-centered">
          {{ one_day_ago }} in
        </p>
        <p class="subtitle is-6 is-size-7-mobile has-text-centered">
          Yesterday
        </p>
      </div>
    </div>
  </div>
  <div class="column">
    <div class="card has-background-link-light">
      <div class="card-content">
        <p class="title is-4 is-size-6-mobile has-text-centered">
          {{ five_day_total }} in
        </p>
        <p class="subtitle is-6 is-size-7-mobile has-text-centered">
          Last 5 days
        </p>
      </div>
    </div>
  </div>
  <div class="column">
    <div class="card has-background-link-light">
      <div class="card-content">
        <p class="title is-4 is-size-6-mobile has-text-centered">
          {{ thirty_day_total }} in
        </p>
        <p class="subtitle is-6 is-size-7-mobile has-text-centered">
          Last 30 days
        </p>
      </div>
    </div>
  </div>
</div>

<div class="columns" *ngIf="location">
  <div class="column">
    <div class="card has-background-link-light">
      <div class="card-content">
        <p class="title is-4 is-size-6-mobile has-text-centered">
          {{ this_month }} in
        </p>
        <p class="subtitle is-6 is-size-7-mobile has-text-centered">
          This month
        </p>
      </div>
    </div>
  </div>
  <div class="column">
    <div class="card has-background-link-light">
      <div class="card-content">
        <p class="title is-4 is-size-6-mobile has-text-centered">
          {{ this_year }} in
        </p>
        <p class="subtitle is-6 is-size-7-mobile has-text-centered">
          This year
        </p>
      </div>
    </div>
  </div>
  <div class="column">
    <div class="card has-background-link-light">
      <div class="card-content">
        <p class="title is-4 is-size-6-mobile has-text-centered">
          {{ last_year }} in
        </p>
        <p class="subtitle is-6 is-size-7-mobile has-text-centered">
          Last year
        </p>
      </div>
    </div>
  </div>
</div>

<div class="notification is-warning has-text-centered mt-4" *ngIf="five_day_total == 0 && location">
  No rainfall in the past five days 😭
</div>

<div class="chart-container">
  <canvas id="myChart"></canvas>
</div>
